### ISSUE TITLE
Index goes out of sync with big number of rows

### ISSUE THREAD

**Issue by danieleteti** [VSoftTechnologies/VSoft.VirtualListView#3]
Hi Vincent, 
seems that with a big number of rows (I tested with 200000) index goes out of synch and become, sometimes, even negative. 
To reproduce this just set 200000 at [this line](https://github.com/VSoftTechnologies/VSoft.VirtualListView/blob/master/Examples/DemoMain.pas#L55) then run the program and scroll the list using the scrollbar.

Thank you for your support

**Comment by vincentparrett** [comment]
H Daniel

Thanks for the report, I can reproduce this here, strange that I never saw it before. Not sure what is causing this.. scrolling with the keyboard works fine. I'll look into it.

**Comment by vincentparrett** [comment]
Ok, that was interesting, the WM_VSCROLL message only has 16bits of scroll/track position - changed to call GetScrollInfo so it gets the full 32bit value.

**Comment by danieleteti** [comment]
Great, thank you.
